version: "3.7"
services:
  Postgres:
    image: postgres
    container_name: Postgres
    restart: always
    ports:
      - 5436:5432
    volumes:
      - "../.data:/var/lib/postgresql/data"
      - "../.docker/postgres.conf:/etc/postgresql/postgresql.conf"
    env_file:
      - ../.env
  Adminer:
    image: adminer
    container_name: Adminer
    restart: always
    links:
      - Postgres:postgres
    ports:
      - 4444:8080
